export { default as HeaderComponent } from './Header/HeaderComponent'
export { default as SliderComponent } from './Silder/SliderComponent'
export { default as ProductComponent } from './Product/ProductComponent'
export { default as Path } from './Path/PathComponent'
export { default as SizeComponent } from './DetailPage/SizeComponent'
